### ISSUE TITLE
As a player, after having viewed the intermediary leaderboard I want to click a button to indicate that I’m ready for the next round in order to continue with the next round

### ISSUE THREAD

**Issue by LeoHorv** [sopra-fs24-group-20/sopra-fs24-group-20-server#16]
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#48
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#47
- [x] sopra-fs24-group-20/sopra-fs24-group-20-server#87
