### ISSUE TITLE
As a player, I want to see the final leaderboard in order to see which placement I have in the ranking and to see all the final rankings and points of the other players.

### ISSUE THREAD

**Issue by LeoHorv** [sopra-fs24-group-20/sopra-fs24-group-20-server#17]
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#24
- [x] sopra-fs24-group-20/sopra-fs24-group20-server#59
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#25
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#26
