### ISSUE TITLE
As a player, I want to be able to create a new lobby in order to play with other players

### ISSUE THREAD

**Issue by LeoHorv** [sopra-fs24-group-20/sopra-fs24-group-20-server#2]
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#4
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#5
- [x] sopra-fs24-group-20/sopra-fs24-group20-server#27
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#8
- [x] #29
