### ISSUE TITLE
As a player, I want to join a lobby to play with the players in the lobby I just joined

### ISSUE THREAD

**Issue by LeoHorv** [sopra-fs24-group-20/sopra-fs24-group-20-server#3]
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#9
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#10
- [x] sopra-fs24-group-20/sopra-fs24-group20-server#32
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#11
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#12
- [x] sopra-fs24-group-20/sopra-fs24-group20-server#35
