### ISSUE TITLE
As the lobby host, I want to adjust the game settings in order to personalize the game

### ISSUE THREAD

**Issue by LeoHorv** [sopra-fs24-group-20/sopra-fs24-group-20-server#4]
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#52
- [x] sopra-fs24-group-20/sopra-fs24-group-20-server#95
- [x] sopra-fs24-group-20/sopra-fs24-group-20-server#96
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#51
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#71
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#73
