### ISSUE TITLE
As a player, I want to be able to press a button that I’m ready in order to let the game begin. 

### ISSUE THREAD

**Issue by LeoHorv** [sopra-fs24-group-20/sopra-fs24-group-20-server#6]
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#13
- [x] sopra-fs24-group-20/sopra-fs24-group20-server#37
- [x] sopra-fs24-group-20/sopra-fs24-group20-server#38
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#14
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#15
