### ISSUE TITLE
As a player I want to get from the start screen to the profile screen in order to be able to play a the game with a lobby.

### ISSUE THREAD

**Issue by LeoHorv** [sopra-fs24-group-20/sopra-fs24-group-20-server#67]
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#31
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#32
- [x] sopra-fs24-group-20/sopra-fs24-group20-server#71
- [x] sopra-fs24-group-20/sopra-fs24-group20-server#72
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#30
