### ISSUE TITLE
As a player, I receive a random letter and aim to fill in a word for each category starting with that letter to earn points.

### ISSUE THREAD

**Issue by LeoHorv** [sopra-fs24-group-20/sopra-fs24-group-20-server#7]
- [x] sopra-fs24-group-20/sopra-fs24-group20-server#41
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#16
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#17
