### ISSUE TITLE
As a registered player I want to see the statistics of the previous games I played.

### ISSUE THREAD

**Issue by LeoHorv** [sopra-fs24-group-20/sopra-fs24-group-20-server#74]
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#46
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#82
- [ ] sopra-fs24-group-20/sopra-fs24-group-20-server#84
