### ISSUE TITLE
As a player I want to be able to play as a guest in order to play as a guest

### ISSUE THREAD

**Issue by LeoHorv** [sopra-fs24-group-20/sopra-fs24-group-20-server#78]
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#45
- [x] sopra-fs24-group-20/sopra-fs24-group-20-server#80
- [x] sopra-fs24-group-20/sopra-fs24-group-20-server#81
- [ ] sopra-fs24-group-20/sopra-fs24-group-20-client#44
