### ISSUE TITLE
As a player I want to be able to press a "Stop" button as soon as I have filled in all text fields to end the round for everyone.

### ISSUE THREAD

**Issue by LeoHorv** [sopra-fs24-group-20/sopra-fs24-group-20-server#8]
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#18
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#19
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#20
- [x] sopra-fs24-group-20/sopra-fs24-group20-server#47
- [x] #77
