### ISSUE TITLE
As a player, I am transferred to an overview screen where I can see both my answers and those of my competitors in order to evaluate the answers. 

### ISSUE THREAD

**Issue by LeoHorv** [sopra-fs24-group-20/sopra-fs24-group-20-server#9]
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#21
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#22
- [x] sopra-fs24-group-20/sopra-fs24-group20-server#50
- [x] sopra-fs24-group-20/sopra-fs24-group20-server#52
- [x] sopra-fs24-group-20/sopra-fs24-group20-server#54
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#60
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#68
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#101
