### ISSUE TITLE
As the developer, I want to make sure the code I produced works in order to have a functional application.

### ISSUE THREAD

**Issue by LeoHorv** [sopra-fs24-group-20/sopra-fs24-group-20-server#98]
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#62
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#66
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#67
- [x]  sopra-fs24-group-20/sopra-fs24-group-20-client#74
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#77
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#79
- [x] sopra-fs24-group-20/sopra-fs24-group-20-server#128
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#81
- [x] sopra-fs24-group-20/sopra-fs24-group-20-server#118
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#96
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#97
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#110
- [x] #142
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#111
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#114
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#111
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#128
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#129
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#116
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#117
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#119
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#115
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#120
- [x] sopra-fs24-group-20/sopra-fs24-group-20-server#143
- [x] sopra-fs24-group-20/sopra-fs24-group-20-server#145
- [x] sopra-fs24-group-20/sopra-fs24-group-20-server#146
- [x] sopra-fs24-group-20/sopra-fs24-group-20-server#147
- [x] sopra-fs24-group-20/sopra-fs24-group-20-server#148
